import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai_Looped, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const ibmPlexSansThaiLooped = IBM_Plex_Sans_Thai_Looped({
  weight: ["400", "500", "600", "700"],
  subsets: ["thai"],
});

const lora = Lora({
  weight: ["400", "500", "600", "700"],
  variable: "--lora-font-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(ibmPlexSansThaiLooped.className, lora.className)}>
        <div className="h-screen w-screen bg-background-secondary">
          {children}
        </div>
      </body>
    </html>
  );
}
